// src/services/ai.js

export const generateCode = async (layout, theme) => {
    // Mock AI code generation for hackathon
    // In production, this would call an AI API

    const appJsx = `import { useState } from 'react';

function App() {
  return (
    <div className="min-h-screen bg-gray-100">
      <h1 className="text-4xl font-bold text-center py-8">
        Generated Website
      </h1>
      <p className="text-center text-gray-600">
        Theme: ${theme}
      </p>
      <div className="max-w-6xl mx-auto p-4">
        {/* Generated sections will appear here */}
        <p className="text-sm text-gray-500">
          This is a mock generated website. 
          In production, this would be AI-generated based on your layout.
        </p>
      </div>
    </div>
  );
}

export default App;
`;

    const indexCss = `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
`;

    const readme = `# Generated Website

This project was generated by the AI Website Builder.

## Setup

\`\`\`bash
npm install
npm run dev
\`\`\`

## Tech Stack

- React
- Vite
- Tailwind CSS

## Theme

${theme}

## Layout

${JSON.stringify(layout, null, 2)}
`;

    return {
        'src/App.jsx': appJsx,
        'src/index.css': indexCss,
        'README.md': readme
    };
};
