// src/services/ai.js
import { GoogleGenerativeAI } from '@google/generative-ai';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

export const generateCode = async (layout, theme) => {
  try {
    const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash-exp' });

    const prompt = `You are an expert React developer. Generate a complete, production-ready React component based on the following website layout and theme.

Theme: ${theme}
Layout: ${JSON.stringify(layout, null, 2)}

Requirements:
1. Generate ONLY the App.jsx code - no explanations, no markdown formatting
2. Use React hooks (useState, useEffect) where appropriate
3. Use Tailwind CSS for styling
4. Make it responsive and modern
5. Include all sections from the layout array
6. Apply the theme colors consistently
7. Make sure all text content is editable and comes from the layout data
8. Use proper component structure

Return ONLY the raw JavaScript code for App.jsx, nothing else.`;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    const generatedCode = response.text();

    // Clean up any markdown formatting if present
    let appJsx = generatedCode
      .replace(/```javascript\n?/g, '')
      .replace(/```jsx\n?/g, '')
      .replace(/```\n?/g, '')
      .trim();

    const indexCss = `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
`;

    const readme = `# Generated Website

This project was generated by the AI Website Builder using Google Gemini.

## Setup

\`\`\`bash
npm install
npm run dev
\`\`\`

## Tech Stack

- React
- Vite
- Tailwind CSS

## Theme

${theme}

## Layout

${JSON.stringify(layout, null, 2)}
`;

    return {
      'src/App.jsx': appJsx,
      'src/index.css': indexCss,
      'README.md': readme
    };
  } catch (error) {
    console.error('Gemini API Error:', error);

    // Fallback to basic template if AI fails
    const fallbackAppJsx = `import { useState } from 'react';

function App() {
  return (
    <div className="min-h-screen bg-gray-100">
      <h1 className="text-4xl font-bold text-center py-8">
        Generated Website
      </h1>
      <p className="text-center text-gray-600">
        Theme: ${theme}
      </p>
      <div className="max-w-6xl mx-auto p-4">
        <p className="text-sm text-gray-500">
          AI generation temporarily unavailable. Using fallback template.
        </p>
      </div>
    </div>
  );
}

export default App;
`;

    return {
      'src/App.jsx': fallbackAppJsx,
      'src/index.css': `@tailwind base;\n@tailwind components;\n@tailwind utilities;`,
      'README.md': `# Generated Website\n\nTheme: ${theme}`
    };
  }
};
