import express from 'express';
import Project from '../models/Project.js';
import { generateCode } from '../services/ai.js';
import { createZip } from '../services/zip.js';
import { themes } from '../config/themes.js';
import { generateSuggestion } from "../services/ai.js";


const router = express.Router();

router.post("/suggest", async (req, res) => {
    try {
        console.log("✅ AI REQUEST:", req.body);
        const { prompt, target, context } = req.body;

        const suggestion = await generateSuggestion({
            prompt,
            target,
            context
        });

        res.json({ suggestion });

    } catch (error) {
        console.error("Suggest route error:", error);
        res.status(500).json({ error: "AI suggestion failed" });
    }
});

router.post('/:projectId', async (req, res, next) => {
    try {
        const { projectId } = req.params;
        const token = req.headers.authorization?.split('Bearer ')[1];

        const project = await Project.findById(projectId);

        if (!project) {
            return res.status(404).json({ error: 'Project not found' });
        }

        let isOwner = false;

        if (token) {
            try {
                const admin = (await import('../config/firebase.js')).default;
                const decodedToken = await admin.auth().verifyIdToken(token);
                isOwner = decodedToken.uid === project.userId;
            } catch (err) {
            }
        }

        if (!isOwner && !project.isPublic) {
            return res.status(403).json({ error: 'Access denied' });
        }
        const files = {};
        const pages = project.pages && project.pages.length > 0
            ? project.pages
            : [{ name: 'Home', route: '/', layout: project.layout, id: 'default' }];

        const generatedPages = [];

        const pageRouteMap = pages.reduce((acc, page) => {
            acc[page.id] = page.route;
            return acc;
        }, {});

        // Resolve theme object
        const themeName = project.theme || 'light';
        console.log('Resolving theme for project:', projectId, 'Theme Name:', themeName);

        const themeObj = themes[themeName] || themes.light;
        console.log('Resolved Theme Object:', themeObj ? 'Found' : 'Not Found');

        if (!themeObj) {
            console.error('CRITICAL: Theme object format invalid or missing');
        }

        // Generate code for each page
        for (const page of pages) {
            const pageName = page.name || 'Page';
            const componentName = pageName.replace(/\s+/g, '');

            console.log(`Generating code for page: ${pageName} (${componentName})`);

            try {
                // Pass resolved theme object to AI
                const pageCode = await generateCode({ ...page, name: pageName }, themeObj, pageRouteMap);
                console.log(`Successfully generated code for ${pageName}`);

                files[`src/pages/${componentName}.jsx`] = pageCode;
                generatedPages.push({ componentName, route: page.route || '/' });
            } catch (err) {
                console.error(`Error generating code for page ${pageName}:`, err);
                throw err; // Re-throw to be caught by outer handler
            }
        }

        const appJsx = `
import { Routes, Route } from 'react-router-dom';
${generatedPages.map(p => `import ${p.componentName} from './pages/${p.componentName}';`).join('\n')}

export default function App() {
  return (
    <Routes>
${generatedPages.map(p => `      <Route path="${p.route}" element={<${p.componentName} />} />`).join('\n')}
    </Routes>
  );
}
`;
        files['src/App.jsx'] = appJsx.trim();

        // Add static files
        files['src/index.css'] = `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
`;

        files['README.md'] = `# Generated Website

This project was generated by the AI Website Builder.

## Setup

\`\`\`bash
npm install
npm run dev
\`\`\`
`;

        // Create ZIP
        const zipBuffer = await createZip(files, project.name);

        // Return as base64
        res.json({
            filename: `${project.name.replace(/\s+/g, '-').toLowerCase()}.zip`,
            data: zipBuffer.toString('base64')
        });
    } catch (error) {
        next(error);
    }
});


export default router;
